### ISSUE TITLE
Is it possible to make a profile timer with this library.

### ISSUE THREAD

**Issue by robinpdev** [Kees-van-der-Oord/Arduino-Nano-Every-Timer-Controller-B#6]
Basically, i need to measure how long a function takes to compute withing 100ns accuracy.
Is this possible with this library, is there another way without using external timers?
How would i do this?

**Comment by Kees-van-der-Oord** [comment]
The arduino framework uses the TCB3 for the millis() and micros() functions.
This timer is configured to  3.2 ns/tick.
When using this timer you can measure the timing in 3.2 ns increments.
With the first example below you can measure periods up to 256 * 3.2 ns = 8.192 us.
The second example can measure longer periods, using the overflow counter. 
It is rather tricky because to get consistent values for the timer clock and overflow counters,
you have disable interrupts when reading them. The time the interrupts are disabled should be
shorter than 8 us to prevent that an overflow interrupt is missed.

*** simple example without interrupt disabling (up to 8 us) ***

uint8_t startTick;

void startMeasure() {
   startTick = TCB3.CNTL;
}

double stopMeasure() {
   uint8_t ticks
   double period;
   ticks = TCB3.CNTL - startTick;
   period = ticks  * 3.2; // ns
   return period;
}

*** example with overflow and interrupt disabling ***
uint8_t startTick;
unsigned long startOverflow;

void startMeasure() {
   uint8_t status = SREG;
   cli();
   startTick = TCB3.CNTL;
   startOverflow = timer_overflow_count;  // defined in MegaAvr20Mhz.h
   SREG = status;
}

double stopMeasure() {
   uint8_t stopTick;
   unsigned long stopOverflows;

   uint8_t status = SREG;
   cli();
   stopTick = TCB3.CNTL;
   stopOverflow = timer_overflow_count;  // defined in MegaAvr20Mhz.h
   SREG = status;

   unsigned long overflowCount;
   double period;
   overflowCount = stopOverflow - startOverflow;
   period = overflowCount * 256. 
   period -= startTick;
   period += stopTick;
   period *= 3.2; // ns
   return period;
}

WR,

Kees
